version: "3"
services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: .
    command: bundle exec rails s -p 3055 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3055:3055"
    depends_on:
      - db
volumes:
  bundle:
  db:
